var $codes = {
    //"boobies": '<spamtag><img src="http://i.imgur.com/9g6b5.gif" width="51" height="60" spam="1"></spamtag>', Disabled :3
    "weegee": '<img src="http://i.imgur.com/65QFT.png" width="51" height="60">',
    "umad": '<img src="http://i.imgur.com/kODDJ.gif" width="66" height="46">',
    "nowai": '<img src="http://i.imgur.com/XVR2I.jpg" width="46" height="40">',
    "orly": '<img src="http://i.imgur.com/2cRoc.jpg" width="48" height="44">',
    "yarly": '<img src="http://i.imgur.com/FL5zr.jpg" width="48" height="44">',
    "unamused": '<img src="http://i.imgur.com/xpamg.png" width="40" height="40">',
    "bigbubba": '<img src="http://i.imgur.com/jTtvQ.jpg" width="40" height="55">',
    "invadinggecko": '<img src="http://i.imgur.com/XTRtP.jpg" width="40" height="41">',
    "success": '<img src="http://i.imgur.com/30e00.png" width="28" height="59">',
    "fap": '<img src="http://i.imgur.com/PsY5I.gif" width="33" height="40">',
    "dilbert": '<img src="http://i.imgur.com/VpmN8.jpg" width="56" height="38">',
    "nope": '<img src="http://i.imgur.com/N97Di.png" width="30" height="41">',
    "foreveralone": '<img src="http://i.imgur.com/obllO.png" width="30" height="36">',
    "dolan": '<img src="http://i.imgur.com/gZe9z.png" width="30" height="37">',
    "sanic": '<img src="http://i.imgur.com/CTZGo.png" width="31" height="33">',
    "lolface": '<img src="http://i.imgur.com/jP8QL.png" width="28" height="34">',
    ":3": '<img src="http://i.imgur.com/SAyYM.png" width="30" height="29">',
    "megusta": '<img src="http://i.imgur.com/1x6es.png" width="30" height="31">',
    "pekaface": '<img src="http://i.imgur.com/RQfvp.png" width="25" height="25">',
    "datass": '<img src="http://i.imgur.com/1awtK.png" width="30" height="30">',
    "babyseal": '<img src="http://i.imgur.com/GiBiY.png" width="30" height="21">',
    //"meatspin": '<img src="http://i.imgur.com/nLiEm.gif" width="30" height="30">', Disabled :3
    "umaood": '<img src="http://i.imgur.com/Yk6ZV.png" width="33" height="14">',
    "bagger288": '<img src="http://i.imgur.com/sNwfW.png" width="83" height="28">',
    "facepalm": '<img src="http://i.imgur.com/FGs29.jpg" width="40" height="30">',
    "okay": '<img src="http://i.imgur.com/TN1xn.png" width="21" height="30">',
    "imokwiththis": '<img src="http://i.imgur.com/tyu9p.png" width="29" height="30">',
    "pokerface": '<img src="http://i.imgur.com/gbqK7.png" width="30" height="33">',
    "trollface": '<img src="http://i.imgur.com/idXUK.png" width="30" height="25">',
    "pedobear": '<img src="http://i.imgur.com/vRZA9.png" width="18" height="25">',
    "babby": '<img src="http://i.imgur.com/KMtUc.png" width="20" height="27">',
    "gooby": '<img src="http://i.imgur.com/tZ7uG.png" width="40" height="40">',
    "nigga": '<img src="http://i.imgur.com/eAqvn.jpg" width="20" height="30">',
    "fukkireta": '<img src="http://i.imgur.com/e6oan.gif" width="50" height="37">',
    "pushups": '<img src="http://i.imgur.com/eJZ0L.gif" width="40" height="47">',
    "bro": '<img src="http://i.imgur.com/oMEHr.gif" width="66" height="50">',
    "bikenigger": '<img src="http://i.imgur.com/mAQAc.gif" width="24" height="36">',
    "ecchi": '<img src="http://i.imgur.com/i2SWp.gif" width="60" height="60">',
    "epicsaxguy": '<img src="http://i.imgur.com/aOXm1.gif" width="45" height="45">',
    "snoop": '<img src="http://i.imgur.com/0Bwax.gif" width="20" height="45">',
    "dynamite": '<img src="http://i.imgur.com/0gq5a.gif" width="40" height="40">',
    "lolicatgirls1080p": '<img src="http://i.imgur.com/lwZ8K.gif" width="40" height="31">',
    "birdy": '<img src="http://i.imgur.com/7rhHQ.gif" width="55" height="38">',
    "duane": '<img src="http://i.imgur.com/NSodE.gif" width="55" height="38">',
    "fuckyou": '<img src="http://i.imgur.com/RQ5Au.gif" width="42" height="50">',
    "deowitit": '<img src="http://i.imgur.com/LIe61.gif" width="50" height="31">',
    "daddycool": '<img src="http://i.imgur.com/KWKwd.gif" width="60" height="45">',
    "frog": '<img src="http://i.imgur.com/HK8Mc.gif" width="60" height="44">',
    "dog": '<img src="http://i.imgur.com/wtfdb.gif" width="40" height="49">',
    "timotei": '<img src="http://i.imgur.com/q0erE.gif" width="40" height="40">',
    "omnom": '<img src="http://i.imgur.com/Moz8e.gif"50" height="50">',
    "brody": '<img src="http://i.imgur.com/dVo0h.gif" width="40" height="40">',
    "chikkin": '<img src="http://i.imgur.com/j5Znq.gif" width="50" height="50">',
    "burt": '<img src="http://i.imgur.com/6bkHh.gif" width="50" height="50">',
    "racist": '<img src="http://i.imgur.com/pad58.gif" width="60" height="50">',
    "bateman": '<img src="http://i.imgur.com/sqmG0.gif" width="60" height="60">',
    "meattball": '<img src="http://i.imgur.com/USvG7.gif" width="40" height="40">',
    "o": '<img src="http://i.imgur.com/doRcz.gif" width="40" height="40">',
    "dansen": '<img src="http://i.imgur.com/Pvq0s.gif" width="40" height="40">',
    "clap": '<img src="http://i.imgur.com/qTy2s.gif" width="60" height="40">',
    "rape": '<img src="http://i.imgur.com/LzEUn.gif" width="60" height="40">',
    "pull": '<img src="http://i.imgur.com/fomgV.jpg" width="40" height="40">',
    "mmmm": '<img src="http://i.imgur.com/GDa6R.jpg" width="40" height="40">',
    "gang": '<img src="http://i.imgur.com/5ziar.gif" width="30" height="40">',
    "notcp": '<img src="http://i.imgur.com/O8O7n.gif" width="25" height="38" >',
    "pomf": '<img src="http://i.imgur.com/lotDJ.gif" width="50" height="40" >',
    "usa": '<img src="http://i.imgur.com/AJdq7Xu.gif" width="25" height="25" >',
    "miku": '<img src="http://i.imgur.com/ScyKroE.gif" width="32" height="43" >',
    "dreck": '<img src="http://i.imgur.com/uYK1FIh.jpg" width="40" height="40" >',
    "disguy": '<img src="http://i.imgur.com/QbPMBnT.jpg" width="50" height="50" >',
    "applause": '<img src="http://i.imgur.com/zU4MWxt.gif" width="50" height="50" >',
    "like": '<img src="http://i.imgur.com/LoiLTWx.png" width="30" height="30" >',
    "notsure": '<img src="http://i.imgur.com/NaJOipw.jpg" width="50" height="50" >',
    "gir": '<img src="http://i.imgur.com/RQDcT0t.gif" width="50" height="50" >',
    "bogs": '<img src="http://i.imgur.com/NHWMFAV.png" width="27.2" height="40">',
    "de": '<img width="35" height="35" src="http://i.imgur.com/SPlADEN.gif"></img>',
    "merica": '<img width="35" height="58" src="http://i.imgur.com/slU5Ibx.gif"></img>',
    "sad": '<img width="40" height="50" src="http://i.imgur.com/WGVec1g.png"></img>',
    "feelsbadman": '<img width="55" height="55" src="http://i.imgur.com/D5Pb9CK.png"></img>',
    "kekefeels": '<img width="45" height="58" src="http://i.imgur.com/fjnKFla.jpg"></img>',
    "haveaseat": '<img width="60" height="52" src="http://i.imgur.com/0YH5oDz.jpg"></img>',
    "lewd": '<img width="50" height="53" src="http://i.imgur.com/r6OJDU5.png"></img>',
    "ri": '<img width="60" height="60" src="http://i.imgur.com/nie3Nh1.gif"></img>',
    "lewd2": '<img width="60" height="50" src="http://i.imgur.com/T7dLL62.gif"></img>',
    "desu": '<img width="50" height="50" src="http://i.imgur.com/0k6I3Zy.gif"></img>',
    "pingu": '<img width="60" height="53" src="http://i.imgur.com/Fsu8nCL.gif"></img>',
    "oo": '<img width="50" height="49" src="http://i.imgur.com/ifjt6ru.gif"></img>',
    "break": '<img width="39" height="59" src="http://i.imgur.com/8tv6x2K.gif"></img>',
    "kolbaser": '<img width="59" height="49" src="http://i.imgur.com/B6taC1C.gif"></img>',
    "domo": '<img width="60" height="60" src="http://i.imgur.com/3HnTPO7.gif"></img>',
    "ban": '<img width="60" height="60" src="http://i.imgur.com/tua4xS9.gif"></img>',
    "goyim": '<img width="60" height="60" src="http://i.imgur.com/BsUvgVp.gif"></img>',
    "gal": '<img width="48" height="36" src="http://i.imgur.com/HZTke6f.gif"></img>',
    "swig": '<img width="42" height="42" src="http://i.imgur.com/sMRiQIb.gif"></img>',
    "ding": '<img width="50" height="48" src="http://i.imgur.com/bnp9oUY.gif"></img>',
    "ding2": '<img width="50" height="37" src="http://i.imgur.com/nUkwGjw.gif"></img>',
    "ding3": '<img width="50" height="39" src="http://i.imgur.com/ukOLYYB.gif"></img>',
    "moonstar": '<img width="50" height="50"src="http://i.imgur.com/NbrMHqS.gif"></img>',
    "pizza": '<img width="50" height="34" src="http://i.imgur.com/Afl7ikx.gif"></img>',
    "cone": '<img width="50" height="50" src="http://i.imgur.com/Bh4xIHQ.gif"></img>',
    "cube": '<img width="50" height="44" src="http://i.imgur.com/ZFMmJ6s.gif"></img>',
    "boom": '<img width="50" height="38" src="http://i.imgur.com/Dfa0Lzl.gif"></img>',
    "pingu2": '<img width="49" height="50" src="http://i.imgur.com/nE4w7KQ.gif"></img>',
    "doge": '<img width="50" height="50"src="http://i.imgur.com/VH42csK.jpg"></img>',
    "twerk": '<img width="60" height="60" src="http://i.imgur.com/iHpye3j.gif"></img>',
    "fedora": '<img width="50" height="50" src="http://i.imgur.com/z0ZDirP.jpg"></img>',
    "eddie": '<img width="50" height="50" src="http://i.imgur.com/BfCgaIn.jpg"></img>',
    "motherofgod": '<img width="50" height="38" src="http://i.imgur.com/MYnVAEY.gif"></img>',
    "nor": '<img width="38" height="27" src="http://i.imgur.com/EH5QV1o.gif"></img>',
    "rus": '<img width="50" height="30" src="http://i.imgur.com/TyMO94U.gif"></img>',
    "fin": '<img width="36" height="27" src="http://i.imgur.com/l7jJ2io.gif"></img>',
    "jp": '<img width="36" height="25" src="http://i.imgur.com/HDZMkEw.gif"></img>',
    "ditto": '<img width="50" height="50" src="http://i.imgur.com/N5z94YT.gif"></img>',
    "bibby": '<img width="60" height="60" src="http://i.imgur.com/qcP7VvJ.gif"></img>',
    "lod": '<img width="50" height="37" src="http://i.imgur.com/LOUtPco.gif"></img>',
    "juice": '<img width="50" height="50" src="http://i.imgur.com/eiBNv9r.gif"></img>',
    "uk": '<img width="48" height="26" src="http://i.imgur.com/py9LdMs.gif"></img>',
    "nl": '<img width="48" height="30" src="http://i.imgur.com/P0V0pdT.gif"></img>',
    "mario": '<img width="50" height="50" src="http://i.imgur.com/lXztfQr.gif"></img>',
    "toet": '<img width="50" height="60" src="http://i.imgur.com/Tt3wwHD.png"></img>',
    "rinus": '<img width="34" height="60" src="http://i.imgur.com/zDFX7cY.gif"></img>',
    ":o": '<img width="50" height="49" src="http://i.imgur.com/cw2K1qQ.gif"></img>',
    "boogie": '<img width="60" height="60" src="http://i.imgur.com/6aqGVba.gif"></img>',
    "disco": '<img width="46" height="60" src="http://i.imgur.com/DaUdTh0.gif"></img>',
    "dimitri": '<img width="60" height="45" src="http://i.imgur.com/jlKB9id.gif"></img>',
    "mewte": '<img width="60" height="45" src="http://i.imgur.com/aHk0nnU.gif"></img>',
    "sealspin": '<img width="34" height="59" src="http://i.imgur.com/qBQ6pfa.gif"></img>',
    "bestkorea": '<img width="49" height="38" src="http://i.imgur.com/07PSF6t.gif"></img>',
    "sk": '<img width="50" height="38" src="http://i.imgur.com/DyFgOPw.gif"></img>'
};